export const skillsData = [
  "HTML",
  "CSS",
  "JavaScript",
  "React",
  "Next.js",
  "Node.js",
  "TypeScript",
  "Git",
  "Tailwind CSS",
  "Prisma",
  "MongoDB",
  "Express",
  "MySQL",
  "Framer Motion",
  "Bootstrap",
  "React-native",
  "C",
  "C++",
] as const;
export type SKillsType = (typeof skillsData)[number];
export const experienceData = [
  {
    title: "Software Engineer",
    company: "Vesko",
    location: "Finland",
    timeline: "Jan 2025 - Present",
  },
  {
    title: "Application Developer Intern",
    company: "Kesko Oyj",
    location: "Finland",
    timeline: "June 2024 - Dec 2024",
  },
  {
    title: "IT Support",
    company: "Kang Hydropower Company Pvt. Ltd",
    location: "Nepal",
    timeline: "Aug 2020 - Nov 2022",
  },
];
export const projectData = [
  {
    shortTitle: "Post:Blog App",
    title: "Post: Blogging App",
    id: "PostBlogApp",
    description: "Full stack Blogging App",
    fullImage: "/projects/post-blog-4.png",
    logo: "/projects/post-blog-logo.png",
    demo: "https://kumang-subba.github.io/post-webapp/",
    repo: "https://github.com/kumang-subba/post-webapp",
  },
  {
    shortTitle: "Tune",
    title: "Tune: Music App",
    id: "Tune",
    description: "SPA made using without any frameworks / libraries",
    fullImage: "/projects/tune-full.png",
    logo: "/projects/tune-logo.svg",
    demo: "https://main--kumang-tune.netlify.app",
    repo: "https://github.com/kumang-subba/Tune",
  },
  {
    shortTitle: "NextCord",
    title: "NextCord: Discord Clone",
    id: "Nextcord",
    description: "Discord clone using Next.js",
    fullImage: "/projects/nextcord-full.png",
    logo: "/projects/nextcord-logo.png",

    demo: "https://nextcord.onrender.com/",
    repo: "https://github.com/kumang-subba/nextcord",
  },
  {
    shortTitle: "The Hub",
    title: "The Hub: The Movie App",
    id: "Thehub",
    description: "The Movie App using TMDb API",
    fullImage: "/projects/the-hub-full.png",
    logo: "/projects/the-hub-logo.png",
    demo: "https://kumang-subba.github.io/the-hub/",
    repo: "https://github.com/kumang-subba/the-hub",
  },
  {
    shortTitle: "Shoppio",
    title: "Shoppio: Ecommerce platform",
    id: "Shoppio",
    description: "Ecommerce platform for selling products",
    fullImage: "/projects/shoppio-full.png",
    logo: "/projects/shoppio-logo.png",
    demo: "https://kumang-subba.github.io/shoppio/",
    repo: "https://github.com/kumang-subba/shoppio",
  },
];
export type ProjectType = (typeof projectData)[number];
